dbfilename redis_cache.rdb
dir /home/avanthika/new/frappe-bench/config/pids
pidfile /home/avanthika/new/frappe-bench/config/pids/redis_cache.pid
bind 127.0.0.1
port 13005
maxmemory 333mb
maxmemory-policy allkeys-lru
appendonly no

save ""


aclfile /home/avanthika/new/frappe-bench/config/redis_cache.acl
